name: "Hey · IT Guy!"
description: "Jimmy's Blog, focus on Perl, Linux, infra automation, Storage/NetAPP, Open Source and so on."
url: "http://zhangchl007.github.io/"
markdown: redcarpet
highlighter: pygments
exclude: ["fabfile.py*", "*.bak"]
